### ISSUE TITLE
trying to use gnuplot with OliWeb

### ISSUE THREAD

**Issue by bluesforsalvador** [m2ware/OliWeb#2]
Hello,

I'm trying to run the gnuplot program from a cgi file.  It seems to run fine on the terminal but cannot run when executed by the cgi.  Any Ideas?

```
MyCgi/htmlStart.cgi

echo 'printing voltage plot'
echo '<br><br>'
echo 'test'
pwd
./MyScripts/sh/create_plot.sh

echo '<img src="pictures/plot/plot.png"/><br>'

echo '<br><br>'

echo '<a href="/Data_Files/data.dat">List of Data</a><br />'

echo '</html>'

```

create_plot.sh is below:

```
#!/bin/sh

gnuplot gnuplot_script
sudo chmod 777 plot.png

cp plot.png MyWeb/pictures/plot/plot.png
rm plot.png
```

gnuplot_script is below:

```
set term png
set output "plot.png"
plot "data.dat"
quit
```

**Comment by bluesforsalvador** [comment]
Hey, thanks for the responses!  I ended up getting it to work here is what I have:
http://i.imgur.com/ukMwLlS.png

**Comment by T3am5hark** [comment]
Excellent!  This is pretty cool - is this a home solar system?  Let me know if there’s anything else I can help with in the web server department.

~Jeff
