### ISSUE TITLE
Creating init-scripts for OliWeb

### ISSUE THREAD

**Issue by totallymaxed** [m2ware/OliWeb#3]
Hi,

I'm trying to setup an init-script for OliWeb on a RaspberryPi running Raspbian using the template below;

https://github.com/fhd/init-script-template

I get a 'command not found' error in /var/log/OliWeb.err when I attemp to manually start the server with;

sudo /etc/init.d/oliweb-server

Any ideas about why I get this error would be useful. Alternatively is there an alternative menthod for having OliWeb auto start on boot?

Thanks

Andy

**Comment by T3am5hark** [comment]
FYI - I've just added start on boot capability.  would love to have Guinea pigs... Err, testers!
