### ISSUE TITLE
installed in different directory

### ISSUE THREAD

**Issue by bluesforsalvador** [m2ware/OliWeb#6]
Hi I cloned OliWeb in /home/pi/programs/ directory and it doesn't seem to work.
I can go to <my ip address>:8077 and I get a blank page (not the index.html)

Should I have cloned it into /home/pi/ ?

I did the sudo make all from /home/pi/programs/OliWeb/ivySox/ and it seemed to install fine.

I also added the 'run from boot' option from the wiki and when I do a 'ps axg | grep OliWeb' I can see the program is running.

Thanks,

Adam

**Comment by bluesforsalvador** [comment]
I'm not getting any logged traffic in the OliWeb.log file:

`******************
** OliWeb 2.0.1 **
******************
[2016-10-2 16:51:07]  Starting OliWeb
[2016-10-2 16:51:07]  Opening port 8077
[2016-10-2 16:51:07]  Listening on port 8077...
`

**Comment by bluesforsalvador** [comment]
`pi@raspberrypi:/usr/local/bin $ [2016-10-3 17:15:49]  Opening OliWebConfig.xml
Reading configuration parameters
PortNumber = 8077
RootFileDirectory = web
DefaultFileName = index.html
FileNotFoundPage = oops404.html
ScriptDirectory = cgi-bin
LogFile = OliWeb.log
PhpEngine = /usr/bin/php
PhpFlags = -f
PythonEngine = /usr/bin/python
PythonFlags =
UtilDirectory = util
LogLevel = medium
LogLevel = 3
******************
** OliWeb 2.0.1 **
******************
[2016-10-3 17:15:49]  Starting OliWeb
[2016-10-3 17:15:49]  Opening port 8077
bindSocket...: Address already in use
[2016-10-3 17:15:49]  Listening on port 8077...
`

**Comment by T3am5hark** [comment]
Hi there,

You should be able to install it anywhere - location doesn't matter.  I do see that the BindSocket shows port already in use.  If there's another OliWeb process running already you may have to kill it at the system level ( "ps -ef | grep OliWeb" will find you the process, which you can then kill ).

There's facilities in there also to install OliWeb so that it will use an alternate directory location - I'll check the Wiki to see if those instructions are up to date.

**Comment by T3am5hark** [comment]
With relative paths for web and cgi-bin you also have to invoke from the ivySox directory.  If you want to invoke from outside of that directory, the config needs to specify absolute paths - that would be the next thing to try.

**Comment by bluesforsalvador** [comment]
Thanks!

It was the absolute paths that did it.
Thanks again for continuing support!  I love OliWeb for my small projects and stuff.


-Adam

**Comment by T3am5hark** [comment]
Great!  Glad that did the trick.
